#include "app/ChartTags.hpp"
#include "app/Version.hpp"
#include "core/format/OjnParser.hpp"

#include <string>
#include <utility>

namespace renderojn::app {

output::Tags build_chart_tags(const format::OjnHeader& header, const io::ByteBuffer& normalized, bool include_cover,
                              Diagnostics& diagnostics) {
    output::Tags tags;
    tags.title = header.title;
    tags.artist = header.artist;
    tags.track = header.song_id;
    tags.genre = format::genre_name(header.genre, diagnostics);
    tags.comment = std::string("Generated by RenderOJN v") + version::kVersion + "\n" + version::kProjectUrl;
    if (include_cover) {
        if (auto cover = format::extract_cover_art(normalized, header, diagnostics)) {
            tags.cover = std::move(cover->bytes);
            tags.cover_mime = std::move(cover->mime);
        }
    }
    return tags;
}

} // namespace renderojn::app
