using System;
using System.Diagnostics;
using TagLib;

namespace O2JamConverter
{
    public static class Encoder
    {
        public static bool EncodeToMp3(string wavPath, string mp3Path)
        {
            // We assume 'lame' is in the system's PATH.
            // Using -V 2 for high quality VBR, a good default.
            string arguments = $"-V 2 \"{wavPath}\" \"{mp3Path}\"";
            try
            {
                using (var process = new Process())
                {
                    process.StartInfo = new ProcessStartInfo
                    {
                        FileName = "lame",
                        Arguments = arguments,
                        UseShellExecute = false,
                        RedirectStandardOutput = true,
                        RedirectStandardError = true,
                        CreateNoWindow = true,
                    };

                    process.Start();
                    string stdOut = process.StandardOutput.ReadToEnd();
                    string stdErr = process.StandardError.ReadToEnd();
                    process.WaitForExit();

                    if (process.ExitCode != 0)
                    {
                        Console.WriteLine("LAME encoder failed.");
                        Console.WriteLine("STDOUT: " + stdOut);
                        Console.WriteLine("STDERR: " + stdErr);
                        return false;
                    }
                    return true;
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("Failed to run LAME encoder. Is 'lame' installed and in your PATH?");
                Console.WriteLine(ex.Message);
                return false;
            }
        }

        public static void TagMp3(string mp3Path, MusicHeader header)
        {
            try
            {
                var file = TagLib.File.Create(mp3Path);
                file.Tag.Title = header.Title;
                file.Tag.Performers = new[] { header.Artist };
                file.Tag.AlbumArtists = new[] { header.Charter }; // Using AlbumArtists for the charter.
                file.Tag.Genres = new[] { MapGenre(header.NewGenreCode) };
                // file.Tag.Track = (uint)header.NewSongID; // NewSongID can be 0, which is invalid for Track.

                file.Tag.Comment = "Generated by O2JamConverter";

                file.Save();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Failed to write tags to {mp3Path}: {ex.Message}");
            }
        }

        private static string MapGenre(uint genreCode)
        {
            // This mapping is from the C++ source code.
            string[] genres = { "Ballad", "Rock", "Dance", "Techno", "Hip-hop", "Soul/R&B", "Jazz", "Funk", "Classical", "Traditional", "Etc" };
            if (genreCode < genres.Length)
            {
                return genres[genreCode];
            }
            return "Etc";
        }
    }
}
