import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  globalIgnores(['dist']),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      globals: globals.browser,
    },
  },
  {
    // Generated by the shadcn CLI and regenerated by it on every update, so
    // local edits to satisfy a lint rule would be overwritten. These files
    // export a cva variants object beside their component, which is upstream's
    // convention; the rule only guards Fast Refresh in dev, so switching it
    // off here costs nothing and keeps `npm run lint` meaningful everywhere
    // else.
    files: ['src/components/ui/**/*.{ts,tsx}'],
    rules: {
      'react-refresh/only-export-components': 'off',
    },
  },
  {
    // Tests reach for Node built-ins (zlib.crc32 as an independent CRC oracle)
    // and export helper factories, which the react-refresh rule flags in .tsx.
    files: ['tests/**/*.{ts,tsx}'],
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
    },
    rules: {
      'react-refresh/only-export-components': 'off',
    },
  },
])
