import { defineConfig } from "vitest/config"

/*
 * Separate from vite.config.ts on purpose: the app config carries
 * `base: "/render-ojn/"` and the Tailwind plugin, neither of which tests need,
 * and Tailwind adds real startup cost to every run. Only the `@` alias is
 * shared, restated here so the two cannot silently diverge.
 */
export default defineConfig({
  resolve: {
    alias: { "@": new URL("./src/", import.meta.url).pathname },
  },
  test: {
    // Most of the suite is pure logic. The three files that need a DOM opt in
    // with a `// @vitest-environment jsdom` docblock, so the rest stays fast.
    environment: "node",
    // @testing-library/react registers its auto-cleanup on a global afterEach,
    // which it only does when globals are enabled. Without this each test's
    // hook stays mounted into the next one and renderHook returns a null
    // result.current. Tests still import test/expect explicitly.
    globals: true,
    include: ["tests/**/*.test.ts", "tests/**/*.test.tsx"],
    setupFiles: ["./tests/setup.ts"],
    coverage: {
      provider: "v8",
      include: ["src/**"],
      exclude: [
        // Vendored shadcn output, regenerated by the CLI and tested upstream.
        "src/components/ui/**",
        // Emscripten build artifacts; git-ignored and absent on a fresh clone.
        "src/wasm/**",
        // Imports the WASM glue at module scope, so it cannot be collected.
        "src/workers/**",
        // Test infrastructure, scheduled for removal.
        "src/lib/stub.ts",
        // Top-level side effects and pure prop wiring respectively.
        "src/main.tsx",
        "src/App.tsx",
        "**/*.d.ts",
      ],
      /*
       * Set just below what the suite achieves today, so the ratchet is real
       * but the build is not red on arrival. Per-file rather than one global
       * number, which is gameable by covering only the easy modules.
       *
       * zip.ts sits lower on purpose: its `size > 4 GiB` and `offset > 4 GiB`
       * branches need genuine 4 GiB buffers to reach, and faking them would
       * mean reshaping production code to suit a test.
       */
      thresholds: {
        "src/lib/pairing.ts": { statements: 90, branches: 80, functions: 90 },
        "src/lib/worker-client.ts": { statements: 95, branches: 85, functions: 95 },
        "src/lib/drop.ts": { statements: 90, branches: 90, functions: 85 },
        "src/lib/zip.ts": { statements: 85, branches: 65, functions: 85 },
        "src/hooks/use-queue.ts": { statements: 90, branches: 70, functions: 85 },
        "src/hooks/use-page-drop.ts": { statements: 90, branches: 65, functions: 95 },
      },
    },
  },
})
